# -*- coding: utf-8 -*-
"""nlp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GDBO_NEW3ct8aSgmSxZGS-JX9bWc96vf
"""

from sklearn.feature_extraction.text import TfidfVectorizer

# Example documents
doc1 = "The car is driven on the road."
doc2 = "The truck is driven on the highway."

# List of documents
documents = [doc1, doc2]

# Initialize TF-IDF Vectorizer
vectorizer = TfidfVectorizer()

# Fit the vectorizer to documents and transform the documents
tfidf_vectors = vectorizer.fit_transform(documents)

# Print the vocabulary (terms)
print("Vocabulary (terms):")
print(vectorizer.get_feature_names_out())

# Print TF-IDF vectors for each document
print("\nTF-IDF Vectors:")
for i, doc in enumerate(documents):
    print(f"Document {i + 1}:")
    print(tfidf_vectors[i])
    print()

#import cosine_similarity
from sklearn.metrics.pairwise import cosine_similarity

# Calculate cosine similarity between the documents
cosine_sim = cosine_similarity(tfidf_vectors[0], tfidf_vectors[1]).flatten()[0]

# Print cosine similarity
print(f"Cosine Similarity between document 1 and document 2: {cosine_sim}")